#ifndef __ReaperDialog__
#define __ReaperDialog__

/**
@file
Subclass of ReaperDialogBase, which is generated by wxFormBuilder.
*/

#include "reaperGUI.h"
#include "reaperEntry.h"
#include "reapertypes.h"
#include "functions.h"

struct sqlite3;
class CheckoutThread;

/** Implementing ReaperDialogBase */
class ReaperDialog : public ReaperDialogBase
{
public:
	/** Constructor */
	ReaperDialog( wxWindow* parent );

//    void        AddTextToOutput(wxString sMessage);
    void        AddTextToOutput(wxString sFormat, ...);

    virtual void OnClose( wxCloseEvent& event );
    virtual void OnExit( wxCommandEvent& event );

    virtual void OnProjectChoice( wxCommandEvent& event );
    virtual void OnCheckout( wxCommandEvent& event );
    virtual void OnDirChanged( wxFileDirPickerEvent& event );
    virtual void OnUpdateUI( wxUpdateUIEvent& event );
    virtual void OnCancelCheckout( wxCommandEvent& event );

    virtual void OnCheckoutEvent( wxCommandEvent& event );
    virtual void OnTextEvent( wxCommandEvent& event );

protected:

    void InsertLogo();
    void populate_choice_control();

    static void _outputChar(char ch, void* pUserData);
    void outputChar(char ch);
    static void _printf(void* pUserData, const char* sFormat, ...);
    void vprintf(const char* sFormat, va_list varargs);

private:
    void                SaveSettings();
    void                RestoreSettings();

    STRING              m_sRepoDbPath;
    sqlite3*            m_pDBHandle;
    REAPERENTRY_VECTOR  m_branchVec;
    CheckoutThread*     m_pThread;

    wxString            m_sOutputLine;
};

#endif // __ReaperDialog__
